import os

STORED_CLOUDMAP_PATHS = os.path.join(os.path.expanduser("~"), ".telecloud")
CONFIG_PATH = os.path.join(STORED_CLOUDMAP_PATHS, "config.json")
STORED_PREPARED_FILE_PATHS = os.path.join(STORED_CLOUDMAP_PATHS, "prepared_data")
SESSION_PATH = os.path.join(STORED_CLOUDMAP_PATHS, "session")
CLOUDMAP_PATH = os.path.join(STORED_CLOUDMAP_PATHS, "cloudmap.json")
KEY_TEST_PATH = os.path.join(STORED_CLOUDMAP_PATHS, "key_test")
INCLUDED_CLOUDMAP_PATHS = (STORED_CLOUDMAP_PATHS, CLOUDMAP_PATH)

NAMING_FILE_MAX_LENGTH = 255
NONCE_LENGTH = 12
TAG_LENGTH = 16
CHUNK_LENGTH_FOR_LARGE_FILE = 7 * 1024 * 1024  # 7MB
FILE_PART_LENGTH_FOR_LARGE_FILE = 7 * 7 * 1024 * 1024  # 49MB
